model_name: "naver-clova-ix/donut-base-finetuned-docvqa"
dataset_dir: "../dataset"
output_dir: "../models/donut_finetuned"
training_args:
  per_device_train_batch_size: 2
  learning_rate: 3e-5
  num_train_epochs: 10
  fp16: true
  save_steps: 1000
